### ISSUE TITLE
What version of vllm should we use?

### ISSUE THREAD

**Issue by LSC527** [OpenLLMAI/OpenRLHF#184]
I am using vllm==0.2.2 and run a ray ppo training using vllm engines, but got this error:
```
(LLMRayActor pid=433508) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::LLMRayActor.__init__() (pid=433508, ip=0.0.0.0, actor_id=308f1877a62944c81acf867002000000, repr=<openrlhf.trainer.ray.vllm_engine.LLMRayActor object at 0x7edc5858a7a0>)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 109, in __init__ [repeated 3x across cluster]
(LLMRayActor pid=433508)     self.llm = LLM(*args, **kwargs)
(LLMRayActor pid=433508)     self.llm_engine = LLMEngine.from_engine_args(engine_args)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 242, in from_engine_args
(LLMRayActor pid=433508)     engine = cls(*engine_configs,
(LLMRayActor pid=433508)     self._init_workers(distributed_init_method)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 141, in _init_workers
(LLMRayActor pid=433508)     self._run_workers(
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 746, in _run_workers
(LLMRayActor pid=433508)     self._run_workers_in_batch(workers, method, *args, **kwargs))
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 720, in _run_workers_in_batch
(LLMRayActor pid=433508)     output = executor(*args, **kwargs)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/vllm-0.2.2+cu123-py3.10-linux-x86_64.egg/vllm/worker/worker.py", line 60, in init_model
(LLMRayActor pid=433508)     torch.cuda.set_device(self.device)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 404, in set_device
(LLMRayActor pid=433508)     torch._C._cuda_setDevice(device)
(LLMRayActor pid=433508)   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
(LLMRayActor pid=433508)     torch._C._cuda_init()
(LLMRayActor pid=433508) RuntimeError: No CUDA GPUs are available
```
I have no idea whether this is a vllm version related error, or I did something wrong when launching ray training.
Here is how I launch the training (I have 8 gpus):
```
nohup ray start --head --node-ip-address 0.0.0.0 --num-gpus 8 --block &> ray.log &
cd /openrlhf/examples/scripts
./train_ppo_ray_vllm.sh
```
```
# train_ppo_ray_vllm.sh
set -x 
export PATH=$HOME/.local/bin/:$PATH

ray job submit --address="http://127.0.0.1:8265" \
    --runtime-env-json='{"working_dir": "/openrlhf"}' \
    -- python3 examples/train_ppo_ray.py \
    --ref_num_nodes 1 \
    --ref_num_gpus_per_node 1 \
    --reward_num_nodes 1 \
    --reward_num_gpus_per_node 1 \
    --critic_num_nodes 1 \
    --critic_num_gpus_per_node 2 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 2 \
    --vllm_num_engines 2 \
    --vllm_tensor_parallel_size 1 \
    --pretrain /path/to/opt-125m \
    --reward_pretrain /path/to/opt-125m  \
    --save_path path \
    --micro_train_batch_size 4 \
    --train_batch_size 8 \
    --micro_rollout_batch_size 4 \
    --rollout_batch_size 8 \
    --max_epochs 1 \
    --prompt_max_len 1024 \
    --generate_max_len 1024 \
    --zero_stage 2 \
    --bf16 \
    --actor_learning_rate 5e-7 \
    --critic_learning_rate 9e-6 \
    --inference_tp_size 1 \
    --init_kl_coef 0.01 \
    --prompt_data Open-Orca/OpenOrca,Dahoas/full-hh-rlhf,tasksource/oasst1_pairwise_rlhf_reward \
    --prompt_data_probs 0.4,0.5,0.1 \
    --max_samples 80000 \
    --normalize_reward \
    --actor_init_on_gpu \
    --adam_offload \
    --flash_attn \
    --gradient_checkpointing \
    --perf
```

**Comment by hijkzzz** [comment]
@wuxibin89

**Comment by wuxibin89** [comment]
@LSC527 there is a bug when `vllm_tensor_parallel_size=1`, i will fix it.

**Comment by LSC527** [comment]
Thanks. It works fine now.
